suite-index.mako: add exception handling for suite index page
Add an try-except error handling to the suite index mako template file.
So that the page can still be generated even the data is malformed,
instead of bumping into this error:
    ValueError: need more than 1 value to unpack

Patch has been tested with positive result.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>